import { z } from "zod";
import {
  RecurrenceRuleSchema,
  TaskPrioritySchema,
  TaskStatusSchema,
  TaskSubtaskSchema,
} from "./task.schema";

/**
 * Full task record, shared by the API responses and the offline-first sync
 * (push PUT / pull changes). `id` is generated by the client for offline
 * creations (uuid) or by the server for API-created tasks — it is always
 * accepted as-is by the server so the offline cache and the server agree.
 */
export const TaskDtoSchema = z.object({
  id: z.string().min(1).max(64),
  user_id: z.string().min(1).optional(),
  parent_task_id: z.string().nullable().optional(),
  original_due_date: z.iso.datetime().nullable().optional(),
  title: z.string().min(1).max(200),
  description: z.string().max(2000).nullable().optional(),
  priority: TaskPrioritySchema.optional(),
  status: TaskStatusSchema.optional(),
  due_date: z.iso.datetime().nullable().optional(),
  has_time: z.boolean().optional(),
  tags: z.array(z.string().trim().min(1).max(50)).max(20).optional(),
  subtasks: z.array(TaskSubtaskSchema).max(50).optional(),
  recurrence_rule: RecurrenceRuleSchema.nullable().optional(),
  /** Derived view flags (range/overdue), used by clients. */
  is_instance: z.boolean().optional(),
  is_occurrence: z.boolean().optional(),
  occurrence_date: z.iso.datetime().nullable().optional(),
  deleted_at: z.iso.datetime().nullable().optional(),
  created_at: z.iso.datetime().optional(),
  updated_at: z.iso.datetime(),
});
export type TaskDto = z.infer<typeof TaskDtoSchema>;

export const CreateTaskSchema = z
  .object({
    title: z.string().min(1).max(200),
    description: z.string().max(2000).optional(),
    priority: TaskPrioritySchema.optional(),
    status: TaskStatusSchema.optional(),
    due_date: z.iso.datetime().nullable().optional(),
    has_time: z.boolean().optional(),
    tags: z.array(z.string().trim().min(1).max(50)).max(20).optional(),
    subtasks: z.array(TaskSubtaskSchema).max(50).optional(),
    recurrence_rule: RecurrenceRuleSchema.nullable().optional(),
  })
  // A recurring parent is the series anchor: it needs a first occurrence.
  .refine(
    (dto) =>
      dto.recurrence_rule === undefined ||
      dto.recurrence_rule === null ||
      (dto.due_date !== undefined && dto.due_date !== null),
    {
      message: "A recurring task requires a due_date (first occurrence)",
    }
  );
export type CreateTaskDto = z.infer<typeof CreateTaskSchema>;

/**
 * Generic PATCH. `due_date: null` clears the date (dated ↔ backlog conversion).
 * For a recurring parent, the client sends the mutated occurrence
 * instant via the `?occurrence_date=` query param — the server then
 * materializes an instance instead of touching the parent.
 */
export const UpdateTaskSchema = z.object({
  title: z.string().min(1).max(200).optional(),
  description: z.string().max(2000).nullable().optional(),
  priority: TaskPrioritySchema.optional(),
  status: TaskStatusSchema.optional(),
  due_date: z.iso.datetime().nullable().optional(),
  has_time: z.boolean().optional(),
  tags: z.array(z.string().trim().min(1).max(50)).max(20).optional(),
  subtasks: z.array(TaskSubtaskSchema).max(50).optional(),
  recurrence_rule: RecurrenceRuleSchema.nullable().optional(),
});
export type UpdateTaskDto = z.infer<typeof UpdateTaskSchema>;

export const TaskFiltersSchema = z.object({
  status: TaskStatusSchema.optional(),
  priority: TaskPrioritySchema.optional(),
  backlog: z.coerce.boolean().optional(),
});
export type TaskFilters = z.infer<typeof TaskFiltersSchema>;

export const TaskRangeQuerySchema = z.object({
  start: z.iso.datetime(),
  end: z.iso.datetime(),
});
export type TaskRangeQuery = z.infer<typeof TaskRangeQuerySchema>;

export const TaskListResponseSchema = z.object({
  data: z.array(TaskDtoSchema),
});
export type TaskListResponse = z.infer<typeof TaskListResponseSchema>;
